### ISSUE TITLE
可以把环境说明一下吗？

### ISSUE THREAD

**Issue by 643435675** [xiaosimao/IP_POOL#2]
我用的的3.6，一些包没有成功安装好，浪费时间了，我从大才哥哥那边找过来的。

**Comment by huifeideyull** [comment]
python3搞半天，没法用，换成2.7.10 可以运行起来。  不得不吐槽下说明文档有点坑啊，运行环境都不标注下

**Comment by xiaosimao** [comment]
恩，虚心接受。
